### ISSUE TITLE
25th word

### ISSUE THREAD

**Issue by Zimulakra** [nautls/nautilus-wallet#116]
I would like to store my NFTs on a ledger using a 25th word, but if for some reason there is a problem with ledger it would be nice to be able to restore the wallet in Nautilus by entering that 25th word.

**Comment by Zimulakra** [comment]
I think it might be useful to have a 25th word (aka passphrase or extension word) even if you are not using a Ledger hardware wallet. You could have one seed phrase, but easy add additional siloed wallets.

**Comment by arobsn** [comment]
Duplicated with #52
