### ISSUE TITLE
I cannot use Nautilus-wallet with my local network

### ISSUE THREAD

**Issue by swag-eag** [nautls/nautilus-wallet#163]
Hi.

I am trying to connect Nautilus-wallet to my local network (ergo.chain.addressPrefix = 96):
Node 1: 

- scorex.network.bindAddress = "0.0.0.0:9022"
- scorex.restApi.bindAddress = "127.0.0.1:9122"

Node 2:

- scorex.network.bindAddress = "0.0.0.0:9023"
- ergo.restApi.bindAddress = "127.0.0.1:9123"

What should I modify in the nautilus-wallet source code to connect to this local blockchain?

Thanks

**Comment by arobsn** [comment]
Hi! You need to rewrite the [graphQlService](https://github.com/nautls/nautilus-wallet/blob/490eb1512b1c0aa2fba309bde7d944bba98b6f9a/src/chains/ergo/services/graphQlService.ts) module using Node's endpoints to have this working. 

Alternatively, you can use [indexed-node-graphql](https://github.com/Luivatra/indexed-node-graphql) as a relay for your local indexed node, this way you don't need to change anything in the Nautilus codebase, just adjust the GraphQL server URL in the settings page.
