### ISSUE TITLE
Migrate from `windicss` to `tailwind`

### ISSUE THREAD

**Issue by arobsn** [nautls/nautilus-wallet#190]
Windi CSS [is no longer maintained](https://windicss.org/posts/sunsetting.html) and should be removed ASAP. The UI rework for mobile build is a nice opportunity to do this.

**Comment by abhijit360** [comment]
I would love to work on this! Could you assign this task to me?

**Comment by arobsn** [comment]
@abhijit360 assigned! Reach me out on Discord or Telegram if you need some clarification.
