### ISSUE TITLE
"empty array" Message when trying to transfer

### ISSUE THREAD

**Issue by Caliboi** [nautls/nautilus-wallet#217]
I am trying to Transfer $Ergo from one Nautilus wallet to another (linked to my ledger nano S) and keep getting the message "Empty array". It does not allow me to proceed with the transaction. Any insight?

<img width="685" alt="Screenshot 2024-11-12 at 9 27 05 PM" src="https://github.com/user-attachments/assets/829796e6-f53c-44c4-97ea-07c6fca4a33e">

**Comment by Emmaward090** [comment]
> I am trying to Transfer $Ergo from one Nautilus wallet to another (linked to my ledger nano S) and keep getting the message "Empty array". It does not allow me to proceed with the transaction. Any insight?
> 
> <img alt="Screenshot 2024-11-12 at 9 27 05 PM" width="685" src="https://private-user-images.githubusercontent.com/188282476/385560525-829796e6-f53c-44c4-97ea-07c6fca4a33e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjU4NDUsIm5iZiI6MTczMTQ2NTU0NSwicGF0aCI6Ii8xODgyODI0NzYvMzg1NTYwNTI1LTgyOTc5NmU2LWY1M2MtNDRjNC05N2VhLTA3YzZmY2E0YTMzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwMjM5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjBjMTc2NjU3YTMyMWEwM2ZmY2ZkZjM2NmU0MDZjOTkwNzljZDRhNjUxMjBlNjc1MzkyZGFhYTMyNDUyNDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BPXBge45COP5_-_9dXSuawUbP0xJkfccYjR1eeEjr98">



We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:NAT#03201
[Nautilus support Network](https://dappsblockchainsupport.42web.io/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by arobsn** [comment]
@Caliboi please, ignore @Emmaward090, it's a scam attempt. Will jump on your issue soon.
