### ISSUE TITLE
Make a landing page 

### ISSUE THREAD

**Issue by esot321c** [nautls/nautilus-wallet#89]
Please create a website so that Nautilus can be linked somewhere besides github. 

All it needs are: 
- A Hero Section that says "Get Nautilus" and links firefox and google play
- A short description of nautilus
- Link to github

What it could also have: 
- guides on how to use nautilus
- links to partnerships and dapps that currently work with nautilus

**Comment by arobsn** [comment]
Landing page is put in place by Koutelier: https://nautiluswallet.com/

Closing this.
